Fix build failure on Solaris 2.9
Declare altzone to avoid the following error:

    ../src/Modules/timemodule.c:1334:30: note: each undeclared
    identifier is reported only once for each function it appears in
    ../src/Modules/timemodule.c: In function 'init_timezone':
    ../src/Modules/timemodule.c:1569:43: error: 'altzone' undeclared
    (first use in this function)
    PyModule_AddIntConstant(m, "altzone", altzone);

(cherry picked from commit c38be0ead0a27a16273eb5d66617dca941b7c7b1)