Build C modules with -static-libgcc on Solaris
Without this patch we have the following error:

ImportError: ld.so.1: python3.7: fatal: libgcc_s.so.1: open failed: No such file or directory
(cherry picked from commit 00f4c2a1d2f9593c166da8d6d6293115bf2a7599)